# Generated by Django 3.1.5 on 2021-01-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favourite',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
