# Generated by Django 3.1.5 on 2021-01-10 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_user_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favourite',
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favourite', models.CharField(blank=True, max_length=250, null=True)),
                ('fav', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to='userauth.user')),
            ],
        ),
    ]
